Repository LJOSC/community-manager-bot, pull requests merged in 2024-06, with the labels that each got.

#2 Send slack message for github star events
  .gitignore
  env.example
  main.js
  package-lock.json
  package.json
  src/app.js
  src/middlewares/verifyGitHubSignature.js
  src/routes/github.js
Labels: feature

#5 Refactor to typescript
  .gitignore
  index.ts
  package-lock.json
  package.json
  src/app.ts
  src/configs/envVars.ts
  src/middlewares/verifyGitHubSignature.js
  src/middlewares/verifyGitHubSignature.ts
  src/routes/github.ts
  tsconfig.json
Labels: enhancement, refactor, typescript

#7 Setup linting
  .eslintignore
  .eslintrc.cjs
  .nvmrc
  .prettierrc
  index.ts
  package-lock.json
  package.json
  src/app.ts
  src/configs/envVars.ts
  src/configs/slack.ts
  src/index.ts
  src/middlewares/verifyGitHubSignature.ts
  src/routes/github/github.routes.ts
  src/routes/index.ts
  tsconfig.json
Labels: enhancement, linting

#9 Setup logger
  .eslintrc.cjs
  package-lock.json
  package.json
  src/configs/envVars.ts
  src/configs/logger.ts
  src/index.ts
  src/routes/github/github.controller.ts
  src/routes/github/github.routes.ts
  src/routes/github/github.service.ts
  src/utils/APIError.ts
  src/utils/format.ts
  src/utils/http-status.ts
  src/utils/logger.ts
Labels: enhancement

#12 Fix build failure bug
  package-lock.json
  package.json
Labels: bug, critical

#14 Greet newly joined members
  env.example
  src/configs/envVars.ts
  src/index.ts
  src/routes/github/github.service.ts
  src/services/index.ts
  src/services/slackGreetMessage.ts
Labels: feature

#15 Containerize the application with multistage builds
  .dockerignore
  Dockerfile
  docker-compose.yaml
  package.json
Labels: docker

#17 Add github actions to deploy on tailscale
  .github/workflows/deploy-on-prod.yaml
  Dockerfile
Labels: docker, ci/cd, tailscale
